## Machine Learning
# Tarea 1 : Problema de Clasificación y de Regresión Lineal
---
__PROFESOR : Rodrigo Hernández__

__ALUMNOS : Roy Barrera - José Pérez__

In [1]:
#Importacion de Librerias

#Manejo de path y carpetas
import os 

#Manejo de Data Frame
import pandas as pd

#Manejo de gráfica
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from pandas.plotting import scatter_matrix

#Magic para graficar dentro del notebook
%matplotlib inline

#Disposición de argumentos de entrada para ML
import numpy as np

#Estadísticos de base
from scipy import stats

#Particiones para muestras
from sklearn.model_selection import train_test_split

#Clasificador Support Vector Machines
from sklearn.svm import SVC

#Métricas de desempeño
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

from sklearn.naive_bayes import GaussianNB

#Modelo de regresión Lineal

from sklearn.linear_model import LinearRegression
from sklearn import model_selection
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm


In [2]:
df_t01 = pd.read_csv('Gasto_x_Familia.csv', sep=';', decimal='.')
df_t02=df_t01.drop(['Gastos','Ingresos','G8_Comunicaciones','G9_Recreacion','G10_Educacion'], axis=1)


In [7]:
import time
import warnings; 
warnings.simplefilter('ignore')

tot_total   = df_t02.shape[0]  # cantidad de datos del dataframe
particiones = 10
tot_grupo   = tot_total // particiones

model_p = SVC(kernel ='poly', cache_size=2048, gamma='auto' ) 


In [10]:
iteracion = 0

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')


>> 13/10/19 13:25:29 Iteracion :  1 , Desde Fila: 0  Hasta Fila: 494
 
>> 13/10/19 13:25:29 SVM con Kernel: LINEAL
 
>> 13/10/19 13:28:06 modelo entrenado!
 
>> 13/10/19 13:28:06 prediccion realizada!
 
[[31 16  1]
 [12 55  7]
 [ 2 13 12]]
              precision    recall  f1-score   support

      1.Bajo       0.69      0.65      0.67        48
     2.Medio       0.65      0.74      0.70        74
      3.Alto       0.60      0.44      0.51        27

   micro avg       0.66      0.66      0.66       149
   macro avg       0.65      0.61      0.62       149
weighted avg       0.66      0.66      0.65       149

>> 13/10/19 13:28:06 modelo evaluado!
 
>> 13/10/19 13:28:06 SVM con Kernel: RADIAL 
 
>> 13/10/19 13:28:06 modelo entrenado!
 
>> 13/10/19 13:28:06 prediccion realizada!
 
[[ 0 48  0]
 [ 0 74  0]
 [ 0 27  0]]
              precision    recall  f1-score   support

      1.Bajo       0.00      0.00      0.00        48
     2.Medio       0.50      1.00      0.66        74
      

>> 13/10/19 13:40:31 modelo entrenado!
 
>> 13/10/19 13:40:31 prediccion realizada!
 
[[36 23  1]
 [17 51  2]
 [ 2 13  4]]
              precision    recall  f1-score   support

      1.Bajo       0.65      0.60      0.63        60
     2.Medio       0.59      0.73      0.65        70
      3.Alto       0.57      0.21      0.31        19

   micro avg       0.61      0.61      0.61       149
   macro avg       0.60      0.51      0.53       149
weighted avg       0.61      0.61      0.60       149

>> 13/10/19 13:40:31 modelo evaluado!
 
>> 13/10/19 13:40:31 SVM con Kernel: RADIAL 
 
>> 13/10/19 13:40:31 modelo entrenado!
 
>> 13/10/19 13:40:31 prediccion realizada!
 
[[ 0 60  0]
 [ 0 70  0]
 [ 0 19  0]]
              precision    recall  f1-score   support

      1.Bajo       0.00      0.00      0.00        60
     2.Medio       0.47      1.00      0.64        70
      3.Alto       0.00      0.00      0.00        19

   micro avg       0.47      0.47      0.47       149
   macro avg  

>> 13/10/19 13:53:54 modelo entrenado!
 
>> 13/10/19 13:53:54 prediccion realizada!
 
[[26 28  1]
 [14 53  4]
 [ 3 13  7]]
              precision    recall  f1-score   support

      1.Bajo       0.60      0.47      0.53        55
     2.Medio       0.56      0.75      0.64        71
      3.Alto       0.58      0.30      0.40        23

   micro avg       0.58      0.58      0.58       149
   macro avg       0.58      0.51      0.52       149
weighted avg       0.58      0.58      0.56       149

>> 13/10/19 13:53:54 modelo evaluado!
 
>> 13/10/19 13:53:54 SVM con Kernel: RADIAL 
 
>> 13/10/19 13:53:54 modelo entrenado!
 
>> 13/10/19 13:53:54 prediccion realizada!
 
[[ 0 55  0]
 [ 0 71  0]
 [ 0 23  0]]
              precision    recall  f1-score   support

      1.Bajo       0.00      0.00      0.00        55
     2.Medio       0.48      1.00      0.65        71
      3.Alto       0.00      0.00      0.00        23

   micro avg       0.48      0.48      0.48       149
   macro avg  

In [ ]:
iteracion = 1

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')



In [ ]:
iteracion = 2

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')



In [ ]:
iteracion = 3

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')




In [ ]:
iteracion = 4

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')



In [ ]:
iteracion = 5

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')



In [ ]:
iteracion = 6

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')



In [ ]:
iteracion = 7

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')



In [ ]:
iteracion = 8

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')



In [ ]:
iteracion = 9

desde = iteracion * tot_grupo    
hasta = desde + tot_grupo

print("==========================================================================================") 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "Iteracion : ", (iteracion +1), ", Desde Fila:", desde, " Hasta Fila:",hasta)

y=df_t02.loc[desde:hasta].Categoria.astype('category')
x=df_t02.loc[desde:hasta].drop('Categoria', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)

print (">>", time.strftime("%d/%m/%y %H:%M:%S"), "SVM con Kernel: POLY ")

#entrenamiento
model_p.fit(x_train, y_train)  # a la maquina le pasa los parametro 
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'modelo entrenado!')

#prediccion
y_pred = model_p.predict(x_test)  # le pide a la maquina que prediga segun los test
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'prediccion realizada!')

#validacion 
print(confusion_matrix(y_test,y_pred))   
print(classification_report(y_test,y_pred))
print (">>", time.strftime("%d/%m/%y %H:%M:%S"), 'datos validados!')

